name: anvilwatch
version: '1.0'
main: com.citrusmc.anvilwatch.AnvilWatch
api-version: '1.21'
description: Logs and bans item renaming in anvils for Minecraft 1.21.4
author: Citric
commands:
  anvilwatch:
    description: Manage AnvilWatch plugin
    usage: /<command> <help|reload|add|remove|log> <args>
    aliases: [anw]
permissions:
  anvilwatch.admin:
    description: Receive anvil rename logs and manage plugin
    default: op
  anvilwatch.bypass:
    description: Bypass banned word restrictions
    default: false