name: anvilwatch
version: '${project.version}'
main: com.citrusmc.anvilwatch.AnvilWatch
api-version: '26.2'
description: Logs and bans item renaming in anvils for Minecraft 26.2.*
author: Citric
commands:
  anvilwatch:
    description: Manage AnvilWatch plugin
    usage: /<command> <help|reload|add|remove|log|check|recent> <args>
    aliases: [anw]
permissions:
  anvilwatch.admin:
    description: Receive anvil rename logs and manage plugin
    default: op
  anvilwatch.bypass:
    description: Bypass banned word restrictions
    default: false